services:
  ## docker hub
  dockerhub:
    container_name: registry-docker-hub
    image: registry:latest
    restart: always
    volumes:
      - ./registry-config/registry-dockerhub.yml:/etc/docker/registry/config.yml
    networks:
      - registry


  ## ghcr.io
  ghcr:
    container_name: registry-ghcr
    image: registry:latest
    restart: always
    volumes:
      - ./registry-config/registry-ghcr.yml:/etc/docker/registry/config.yml
    networks:
      - registry

  ## registry.k8s.io
  gcr:
    container_name: registry-k8s
    image: registry:latest
    restart: always
    volumes:
      - ./registry-config/registry-k8s.yml:/etc/docker/registry/config.yml
    networks:
      - registry

  ## k8s.gcr.io
  k8sgcr:
    container_name: registry-k8s-gcr
    image: registry:latest
    restart: always
    volumes:
      - ./registry-config/registry-k8s-gcr.yml:/etc/docker/registry/config.yml
    networks:
      - registry

  ## quay.io
  quay:
    container_name: registry-quay
    image: registry:latest
    restart: always
    volumes:
      - ./registry-config/registry-quay.yml:/etc/docker/registry/config.yml
    networks:
      - registry

  ## UI
  registry-ui:
    container_name: registry-ui
    image: joxit/docker-registry-ui:main-debian
    environment:
      - NGINX_PROXY_PASS_URL=http://registry-docker-hub:5000
      - SINGLE_REGISTRY=true
    restart: always
    networks:
      - registry


  proxy:
    container_name: proxy
    image: nginx:1.27
    restart: always
    volumes:
      - ./nginx-default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - registry

networks:
  registry: